title: Rafael Ferreira da Silva, Ph.D. - Distinguished Research Scientist
description: 'Distinguished Research Scientist at the Oak Ridge National Laboratory. Distinguished Research Scientist and Section Head (Interim) for Data and AI Systems research in the Computer Science and Mathematics division at Oak Ridge National Laboratory (ORNL), leading research and development in AI, data and agentic workflows, and advanced computing systems.'
url: https://rafaelsilva.com

markdown: kramdown
enable-mathjax: yes

permalink: /blog/:title/

include:
  - _pages

# scholar
scholar:
  sort_by: author
  group_by: year
  group_order: descending
  type_order: [article, inproceedings, phdthesis, techreport]
  bibliography_template: bib

exclude:
  - .git
  - .github
  - .idea
  - .jekyll-cache

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
  - jekyll-scholar
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  - jekyll-scholar
